<!DOCTYPE html>
<html class="no-js">
    <head>

        <!-- Meta Tags -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <!-- Page Title -->
        <title>White Website Development</title>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>

        <!-- Stylesheets -->
        <link rel="stylesheet" href="css/fullwidth.css">
        <link rel="stylesheet" href="css/settings.css">

        <link rel="stylesheet" type="text/css" href="css/foundation.css">
        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
        <link rel="stylesheet" href="css/styles.css">

        <!-- requireJS -->
        <script data-main="/js/jean_and_james/main" src="/js/jean_and_james/lib/require.js"></script>
        
    </head>
    <body>
            <!--
            #################################
                Header
            #################################
            -->

            <?php echo $this->partial('partials/header.phtml');?>
            
            
            <?php echo $this->partial('partials/banner.phtml'); ?>


        <!--
        #################################
            Intro text
        #################################
        -->

        <div class="row zindexed introText firstIntro">
            <div class="large-12 columns">
                <h1><span>Jean</span> and <span>James</span></h1>
            </div>
        </div>


        <!--
        #################################
           What we love to do
        #################################
        -->
        
        <?php // echo $this->partial('partials/tri_menu.phtml'); ?>
        

        <!--<div class="divider"></div>-->

        <!--
        #################################
           Portfolio Filter (isotope)
        #################################
        -->

        <?php // echo $this->partial('partials/filterable_menu.phtml'); ?>



        <!--
        #################################
           Team Container
        #################################
        -->
        
        <?php echo $this->partial('partials/team_container.phtml'); ?>


        <div class="divider"></div>
        
        
        <!--
        #################################
           About Us
        #################################
        -->
        
        <?php echo $this->partial('partials/about_us.phtml'); ?>
        


        
        <!--
        #################################
           Project Phases
        #################################
        -->
        
        <?php // echo $this->partial('partials/banner_layered.phtml'); ?>
                    
    

        <!--
        #################################
           Team Container
        #################################
        -->

        <?php // echo $this->partial('partials/team_container_small.phtml'); ?>



        <!--
        #################################
            Testimonials
        #################################
        -->
        
        <?php // echo $this->partial('partials/testimonials.phtml'); ?>


        <!--
        #################################
           Our SKills
        #################################
        -->

        <?php // echo $this->partial('partials/banner_skills.phtml'); ?>

        <!--
        #################################
            Footer Top
        #################################
        -->

        <?php // echo $this->partial('partials/footer_top.phtml'); ?>


        <!--
        #################################
            Footer Bottom
        #################################
        -->

        <div id="footerBottom">
            <div class="row">
                <div class="large-7 columns">
                    <ul class="footerMenu">
                        <li><a href="/">Home</a></li>
                        <li><a href="/">Jean</a></li>
                        <li><a href="/">James</a></li>
                        <li><a href="/">Archive</a></li>
                        <li><a href="/">Contact</a></li>
                    </ul>
                </div>
                <div class="large-5 columns copyright">
                    <a href="http://themeforest.net/user/AVAThemes">All Rights Reserved, AVAThemes 2013</a>
                </div>
            </div>
        </div>
    </body>
</html>
