<div class="about-intro row">
    <div class="large-12 columns">
        <h4 style="margin-top: 0;">Lorem ipsum dolor sit amet, consectetur</h4>
    </div>
</div>


<div class="quote-about row">
    <div class="large-12 columns">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, assumenda, aliquam dolor aut debitis necessitatibus odio id asperiores</p>
    </div>
</div>


<div class="row moreAbout">
    <div class="large-4 columns">
        <h4>Who We Are</h4>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, laborum, libero, exercitationem est quidem molestiae debitis officiis numquam molestias facere hic voluptatem quos deserunt! Provident, quo, eos, amet, harum tempora cupiditate voluptatibus consectetur soluta nemo ipsa ullam placeat itaque vitae.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam, voluptatum, vel, culpa perferendis minus voluptates non dicta officiis illo enim repellat nulla officia dignissimos doloribus?</p>

        <a href="#" class="moreAbout-button">Meet our Team</a>
    </div>
    <div class="large-4 columns">
        <h4>What We Do</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae, quidem perspiciatis enim voluptatem nam molestias labore. Aliquam maxime voluptatem obcaecati rem ad perferendis nulla corporis facilis. Repellat, numquam deserunt minima quam error rem laudantium iusto!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, nisi enim quos quaerat labore repellat deleniti eos nemo ea voluptates.</p>

        <h5><strong>Our Services</strong></h5>
        <ul id="our-services">
            <li>Web Design</li>
            <li>Logo Design</li>
            <li>Branding Design</li>
            <li>Graphics Design</li>
        </ul>

        <a href="#" class="moreAbout-button">View our Portfolio</a>
    </div>
    <div class="large-4 columns">
        <h4>Where We Are</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos, harum, fuga, et, culpa quae aspernatur sapiente asperiores consequatur necessitatibus doloremque laborum fugiat perspiciatis est repudiandae mollitia! Sequi, fuga eaque facilis!</p>
        <ul id="where-lists">
            <li>Lorem ipsum dolor sit.</li>
            <li>In soluta alias eligendi!</li>
            <li>Nihil aspernatur eos inventore!</li>
            <li>Harum nostrum molestias minima.</li>
        </ul>

        <a href="#" class="moreAbout-button">Send Us a Message</a>
    </div>
</div>