<div id="ourSkills">
            
    <div class="row">

        <div class="large-12 columns">
            <h3 class="skillsTitle">Our <span>Skills</span></h3>
        </div>


        <div class="row progressSkills circ_numbers_holder animationBegin">
            <div class="large-4 small-4 columns circ_counter">
                <canvas width=253 height=253  data-end-nu="79"></canvas>
                <div class="circ_counter_text_holder holder_two"><span class="circ_counter_text text_two"  id="circ_counter_text1"></span><span class="counter_percent_sign">%</span></div>
                <div class="circ_counter_desc">HTML5 and CSS3</div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti qui illo fuga recusandae molestias. Et.</p>
            </div>

            <!-- Progress 2 -->
            <div class="large-4 small-4 columns circ_counter">
                <canvas width=253 height=253  data-end-nu="87"></canvas>
                <div class="circ_counter_text_holder holder_two"><span class="circ_counter_text text_two"  id="circ_counter_text2"></span><span class="counter_percent_sign">%</span></div>
                <div class="circ_counter_desc">jQuery</div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At, atque, voluptate explicabo blanditiis cum unde.</p>
            </div>

            <!-- Progress 3 -->
            <div class="large-4 small-4 columns circ_counter">
                <canvas width=253 height=253  data-end-nu="92"></canvas>
                <div class="circ_counter_text_holder holder_two"><span class="circ_counter_text text_two"  id="circ_counter_text3"></span><span class="counter_percent_sign">%</span></div>
                <div class="circ_counter_desc">Wordpress</div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas, laborum sequi at quis nostrum maxime.</p>
            </div>
        </div>

    </div>

</div>