<div class="fullwidthbanner-container-two">
    <div class="fullwidthbanner-two">
        <ul>
            <!-- THE FIFTH SLIDE -->
            <li data-transition="flyin" data-slotamount="1" data-masterspeed="300" data-thumb="images/thumbs/thumb6.jpg">
                    <img alt="" src="http://placehold.it/1680x712/0eafff/ffffff.png" />

                    <div class="caption large_text team_text sfl"
                            data-x="268"
                            data-y="80"
                            data-speed="300"
                            data-start="1000"
                            data-easing="easeOutExpo"  >Project <span>Phases</span></div>

                    <div class="caption randomrotate"
                            data-x="100"
                            data-y="195"
                            data-speed="1200"
                            data-start="800"
                            data-easing="easeOutExpo"  ><img alt="" src="http://placehold.it/768x474/0eafff/ffffff.png" /></div>

                    <div class="caption sfl responsiveImg3"
                            data-x="-110"
                            data-y="85"
                            data-speed="1400"
                            data-start="2800"
                            data-easing="easeOutExpo"  ><img src="images/slides/text1.png" alt="Image 4"></div>

                    <div class="caption randomrotate responsiveImg3"
                            data-x="910"
                            data-y="385"
                            data-speed="800"
                            data-start="2400"
                            data-easing="easeOutExpo"  ><img src="images/slides/text2.png" alt="Image 4"></div>


                    <div class="caption lfl responsiveImg3"
                            data-x="-200"
                            data-y="425"
                            data-speed="1400"
                            data-start="1300"
                            data-easing="easeOutExpo"  ><img src="images/slides/text3.png" alt="Image 4"></div>
            </li>




                <li data-transition="flyin" data-slotamount="1" data-masterspeed="300" data-thumb="images/thumbs/thumb6.jpg">
                    <img alt="" src="http://placehold.it/1680x712/0eafff/ffffff.png" />

                    <div class="caption large_text team_text sfl"
                            data-x="268"
                            data-y="80"
                            data-speed="300"
                            data-start="1000"
                            data-easing="easeOutExpo"  >Project <span>Phases</span></div>

                    <div class="caption randomrotate"
                            data-x="100"
                            data-y="195"
                            data-speed="1200"
                            data-start="800"
                            data-easing="easeOutExpo"  ><img alt="" src="http://placehold.it/768x474/0eafff/ffffff.png" /></div>

                    <div class="caption sfl responsiveImg3"
                            data-x="-110"
                            data-y="85"
                            data-speed="1400"
                            data-start="2800"
                            data-easing="easeOutExpo"  ><img src="images/slides/text1.png" alt="Image 4"></div>

                    <div class="caption randomrotate responsiveImg3"
                            data-x="910"
                            data-y="385"
                            data-speed="800"
                            data-start="2400"
                            data-easing="easeOutExpo"  ><img src="images/slides/text2.png" alt="Image 4"></div>


                    <div class="caption lfl responsiveImg3"
                            data-x="-200"
                            data-y="425"
                            data-speed="1400"
                            data-start="1300"
                            data-easing="easeOutExpo"  ><img src="images/slides/text3.png" alt="Image 4"></div>
            </li>



        </ul>

        <div class="tp-bannertimer tp-bottom"></div>
    </div>
</div>