<div class="fullwidthbanner-container">
    <div class="fullwidthbanner">
        <ul>
            <li data-transition="flyin" data-slotamount="1" data-masterspeed="300" data-thumb="images/thumbs/thumb6.jpg">
                    <img alt="" src="http://placehold.it/1680x712/0eafff/ffffff.png" />

                    <div class="caption large_text sfl"
                            data-x="178"
                            data-y="200"
                            data-speed="300"
                            data-start="1000"
                            data-easing="easeOutExpo"  >Facilis mag</div>

                    <div class="caption small_text lfl"
                            data-x="200"
                            data-y="293"
                            data-speed="300"
                            data-start="1300"
                            data-easing="easeOutExpo"  >Proin lundium vel ultricies penatibus ac, aliquet mus habitasse penatibus amet vut diam cum</div>


                    <div class="caption small_text button_link sfl"
                            data-x="178"
                            data-y="343"
                            data-speed="300"
                            data-start="1300"
                            data-easing="easeOutExpo"><a href="#" class="hideButton">Click here to learn more about our work</a></div>

                    <div class="caption randomrotate responsiveImg"
                            data-x="-20"
                            data-y="454"
                            data-speed="800"
                            data-start="1600"
                            data-easing="easeOutExpo"  ><img src="images/slides/TP_logo.png" alt="Image 4"></div>
            </li>



            <li data-transition="flyin" data-slotamount="1" data-masterspeed="300" data-thumb="images/thumbs/thumb6.jpg">
                    <img alt="" src="http://placehold.it/1680x712/0eafff/ffffff.png" />


                    <div class="caption randomrotate"
                            data-x="700"
                            data-y="145"
                            data-speed="800"
                            data-start="1600"
                            data-easing="easeOutExpo"  ><img src="images/slides/iphone-white.png" alt="Image 4"></div>



                    <div class="caption large_text sfl"
                            data-x="15"
                            data-y="200"
                            data-speed="300"
                            data-start="1000"
                            data-easing="easeOutExpo"  >Facilis mag</div>


                    <div class="caption small_text homepageSmall lfl"
                            data-x="15"
                            data-y="293"
                            data-speed="300"
                            data-start="1300"
                            data-easing="easeOutExpo"  >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, rem, asperiores tempore <br> sequi perspiciatis error voluptatem quaerat placeat rerum  <br> repellendus voluptatum nobis officia fugiat <br> consequatur inventore vitae saepe ipsa commodi!</div>



                    <div class="caption small_text button_link homepageButton sfl"
                            data-x="15"
                            data-y="443"
                            data-speed="300"
                            data-start="1300"
                            data-easing="easeOutExpo"><a href="#">Find Out More</a></div>



            </li>



            <li data-transition="flyin" data-slotamount="1" data-masterspeed="300" data-thumb="images/thumbs/thumb6.jpg">
                    <img alt="" src="http://placehold.it/1680x712/0eafff/ffffff.png" />


                    <div class="caption randomrotate"
                            data-x="400"
                            data-y="275"
                            data-speed="800"
                            data-start="1600"
                            data-easing="easeOutExpo"  ><img src="images/slides/ipad-white.png" alt="Image 4"></div>



                    <div class="caption large_text sfl"
                            data-x="15"
                            data-y="200"
                            data-speed="300"
                            data-start="1000"
                            data-easing="easeOutExpo"  >Mid in  Turpis</div>


                    <div class="caption small_text homepageSmall lfl"
                            data-x="15"
                            data-y="293"
                            data-speed="300"
                            data-start="1300"
                            data-easing="easeOutExpo"  >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, rem, asperiores tempore <br> sequi perspiciatis error voluptatem quaerat placeat rerum  <br> repellendus voluptatum nobis officia fugiat</div>



                    <div class="caption small_text button_link homepageButton sfl"
                            data-x="15"
                            data-y="543"
                            data-speed="300"
                            data-start="1300"
                            data-easing="easeOutExpo"><a href="#">Find Out More</a></div>



            </li>




        </ul>

        <div class="tp-bannertimer tp-bottom"></div>
    </div>
</div>