<div class="row filterNavigation">
    <div class="large-12 columns">
        <section id="options" class="clearfix">
        <ul id="filters" class="option-set clearfix" data-option-key="filter">
            <li><a class="wb-ico" href="#filter" data-option-value=".web-design">Web Design</a></li>
            <li><a class="pd-ico" href="#filter" data-option-value=".print-design">Print Design</a></li>
            <li><a class="ld-ico" href="#filter" data-option-value=".logo-design">Logo Design</a></li>
            <li><a class="p-ico" href="#filter" data-option-value=".photography">Photography</a></li>
            <li><a class="i-ico" href="#filter" data-option-value=".inspiration">Inspiration</a></li>
            <li><a class="a-ico" href="#filter" data-option-value="*" class="selected">all</a></li>
        </ul>
        </section>
    </div>
</div>





<div class="row" id="container">

    <!-- Element -->
    <div class="element web-design">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element logo-design">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element print-design">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element photography">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element inspiration">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element web-design">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element print-design">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element logo-design">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element inspiration">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element web-design">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

    <!-- Element -->
    <div class="element logo-design">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>


    <!-- Element -->
    <div class="element photography">
        <a href="blog-single.html">
            <img alt="" src="http://placehold.it/244x244/0eafff/ffffff.png" />

            <span>
                <img src="img/home/portfolioIco.png" height="37" width="37" alt="Portfolio Icon">
                <h3>Project Title</h3>
                <h5>Web Design</h5>
                <p>Lorem ipsum dolor sit amet, contur.</p>
                <div class="likes">2</div>
            </span>
        </a>
    </div>

</div>