<div id="footer">

    <div class="row">

        <div class="large-4 footerColumn columns foot1">
            <h4>Link to Visit</h4>
            <p>Here are som einteresting stuff to visit, hope you will enjoy !</p>

            <!-- Link -->
            <a href="#" class="linkHolder">
                <div class="row">
                <div class="large-2 omega columns">
                    <img alt="" src="http://placehold.it/35x35/0eafff/ffffff.png" />
                </div>
                <div class="large-10  alpha columns">
                    <p><span>Nike Web Shop</span> - very fast shipping and top gear</p>
                </div>
                </div>
            </a>

            <!-- Link -->
            <a href="#" class="linkHolder">
                <div class="row">
                <div class="large-2 omega columns">
                    <img alt="" src="http://placehold.it/35x35/0eafff/ffffff.png" />
                </div>
                <div class="large-10  alpha columns">
                    <p><span>Nike Web Shop</span> - very fast shipping and top gear</p>
                </div>
                </div>
            </a>

            <!-- Link -->
            <a href="#" class="linkHolder">
                <div class="row">
                <div class="large-2 omega columns">
                    <img alt="" src="http://placehold.it/35x35/0eafff/ffffff.png" />
                </div>
                <div class="large-10  alpha columns">
                    <p><span>Nike Web Shop</span> - very fast shipping and top gear</p>
                </div>
                </div>
            </a>

            <!-- Link -->
            <a href="#" class="linkHolder">
                <div class="row">
                <div class="large-2 omega columns">
                    <img alt="" src="http://placehold.it/35x35/0eafff/ffffff.png" />
                </div>
                <div class="large-10  alpha columns">
                    <p><span>Nike Web Shop</span> - very fast shipping and top gear</p>
                </div>
                </div>
            </a>
        </div>

        <div class="large-4 footerColumn columns foot2">
            <h4>Latest News</h4>

            <!-- News Holder -->
            <a href="#" class="newsHolder">
                <div class="row">
                    <div class="large-2 omega columns">
                        <img alt="" src="http://placehold.it/35x35/0eafff/ffffff.png" />
                    </div>
                    <div class="large-10 alpha columns">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore id quas voluptas commodi laborum facilis.</p>
                        <span>January 12, 2013 - 9:11 pm</span>
                    </div>
                </div>
            </a>

            <!-- News Holder -->
            <a href="#" class="newsHolder">
                <div class="row">
                    <div class="large-2 omega columns">
                        <img alt="" src="http://placehold.it/35x35/0eafff/ffffff.png" />
                    </div>
                    <div class="large-10 alpha columns">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A, laborum quasi veniam iusto natus quibusdam voluptate beatae velit ex placeat.</p>
                        <span>January 12, 2013 - 9:11 pm</span>
                    </div>
                </div>
            </a>

            <!-- News Holder -->
            <a href="#" class="newsHolder">
                <div class="row">
                    <div class="large-2 omega columns">
                        <img alt="" src="http://placehold.it/35x35/0eafff/ffffff.png" />
                    </div>
                    <div class="large-10 alpha columns">
                        <p>Ut adipiscing enim aliquam ut tristique phasellus. Et aliquet! </p>
                        <span>January 12, 2013 - 9:11 pm</span>
                    </div>
                </div>
            </a>

        </div>

        <div class="large-4 footerColumn columns foot3">
            <h4>Bussines Hours</h4>

            <div class="row">
                <div class="large-12 columns workingSchedule">
                    <p>Monday-Friday: <span>9am to 5pm</span></p>
                    <p>Saturday & Sunday: <span>Closed</span></p>
                </div>
            </div>


            <div class="row">
                <div class="large-12 columns currentTags">
                    <h4>Tags</h4>
                    <a href="#">beautiful</a>
                    <a href="#">design</a>
                    <a href="#">love</a>
                    <a href="#">we</a>
                    <a href="#">inspiration</a>
                    <a href="#">logo</a>
                    <a href="#">print design</a>
                    <a href="#">awesome</a>
                    <a href="#">photography</a>
                    <a href="#">logo design</a>
                    <a href="#">branding</a>
                </div>
            </div>


        </div>

    </div>


</div>