<div class="row" id="header">
            
    <div class="large-2 columns">
        <a href="index.html" class="logoHolder">
            <img src="img/home/logo.png" alt="Featured Logo">
        </a>
    </div>

    <div class="large-8 columns">
        <button class="navButton">Navigation</button>
        <ul id="mainNav">
            <li><a href="/">Home</a></li>
            <li><a href="/">Jean</a>
                <ul>
                    <li><a href="/">Blog</a></li>
                    <li><a href="/">Portfolio</a></li>
                </ul>
            </li>
            <li><a href="/">James</a>
                <ul>
                    <li><a href="/">Blog</a></li>
                    <li><a href="/">Portfolio</a></li>
                </ul>
            </li>
            <li><a href="/">Archive</a></li>
            <li><a href="/">Contact</a></li>
        </ul>
    </div>

    <div class="large-2 columns">
        <ul id="socials">
            <li><a href="#" target="_blank" title="Follow us on Facebook" class="facebook-ico"></a></li>
            <li><a href="#" target="_blank" title="Follow us on Twittwer" class="twitter-ico"></a></li>
        </ul>
    </div>

</div>