<div class="row teamContainer">
            
    <!-- Team Member -->
    <div class="large-4 columns teamMember">
        <div class="teamHolder">
        <img alt="" src="http://placehold.it/308x252/0eafff/ffffff.png" />
        <span>
            <p>Pellentesque eros elit integer, sociis, magna odio scelerisque ac, est enim, auctor natoque risus magnis turpis nisi. Montes duis augue, nunc rhoncus ultricies? Porttitor porttitor</p>
            <ul class="teamSocials">
                <li><a href="#" class="faceIco" target="_blank" title="Follow me on Facebook">Link</a></li>
                <li><a href="#" class="twitterIco" target="_blank" title="Follow me on Twitter">Link</a></li>
                <li><a href="#" class="dribbbleIco" target="_blank" title="Follow me on Dribbble">Link</a></li>
                <li><a href="#" class="linkedIco" target="_blank" title="Follow me on LinkedIn">Link</a></li>
                <li><a href="#" class="vimeoIco" target="_blank" title="Follow me on Vimeo">Link</a></li>
                <li><a href="#" class="flickrIco" target="_blank" title="Follow me on Flickr">Link</a></li>
            </ul>
        </span>
        </div>

        <h2>John Doe</h2>
        <p>PARTNER & UX/UI DIRECTOR</p>

    </div>



    <!-- Team Member -->
    <div class="large-4 columns teamMember">
        <div class="teamHolder">
        <img alt="" src="http://placehold.it/308x252/0eafff/ffffff.png" />
        <span>
            <p>Pellentesque eros elit integer, sociis, magna odio scelerisque ac, est enim, auctor natoque risus magnis turpis nisi. Montes duis augue, nunc rhoncus ultricies? Porttitor porttitor</p>
            <ul class="teamSocials">
                <li><a href="#" class="faceIco" target="_blank" title="Follow me on Facebook">Link</a></li>
                <li><a href="#" class="twitterIco" target="_blank" title="Follow me on Twitter">Link</a></li>
                <li><a href="#" class="dribbbleIco" target="_blank" title="Follow me on Dribbble">Link</a></li>
                <li><a href="#" class="linkedIco" target="_blank" title="Follow me on LinkedIn">Link</a></li>
                <li><a href="#" class="vimeoIco" target="_blank" title="Follow me on Vimeo">Link</a></li>
                <li><a href="#" class="flickrIco" target="_blank" title="Follow me on Flickr">Link</a></li>
            </ul>
        </span>
        </div>

        <h2>John Doe</h2>
        <p>PARTNER & UX/UI DIRECTOR</p>

    </div>



    <!-- Team Member -->
    <div class="large-4 columns teamMember">
        <div class="teamHolder">
        <img alt="" src="http://placehold.it/308x252/0eafff/ffffff.png" />
        <span>
            <p>Pellentesque eros elit integer, sociis, magna odio scelerisque ac, est enim, auctor natoque risus magnis turpis nisi. Montes duis augue, nunc rhoncus ultricies? Porttitor porttitor</p>
            <ul class="teamSocials">
                <li><a href="#" class="faceIco" target="_blank" title="Follow me on Facebook">Link</a></li>
                <li><a href="#" class="twitterIco" target="_blank" title="Follow me on Twitter">Link</a></li>
                <li><a href="#" class="dribbbleIco" target="_blank" title="Follow me on Dribbble">Link</a></li>
                <li><a href="#" class="linkedIco" target="_blank" title="Follow me on LinkedIn">Link</a></li>
                <li><a href="#" class="vimeoIco" target="_blank" title="Follow me on Vimeo">Link</a></li>
                <li><a href="#" class="flickrIco" target="_blank" title="Follow me on Flickr">Link</a></li>
            </ul>
        </span>
        </div>

        <h2>John Doe</h2>
        <p>PARTNER & UX/UI DIRECTOR</p>

    </div>



    <!-- Team Member -->
    <div class="large-4 columns teamMember">
        <div class="teamHolder">
        <img alt="" src="http://placehold.it/308x252/0eafff/ffffff.png" />
        <span>
            <p>Pellentesque eros elit integer, sociis, magna odio scelerisque ac, est enim, auctor natoque risus magnis turpis nisi. Montes duis augue, nunc rhoncus ultricies? Porttitor porttitor</p>
            <ul class="teamSocials">
                <li><a href="#" class="faceIco" target="_blank" title="Follow me on Facebook">Link</a></li>
                <li><a href="#" class="twitterIco" target="_blank" title="Follow me on Twitter">Link</a></li>
                <li><a href="#" class="dribbbleIco" target="_blank" title="Follow me on Dribbble">Link</a></li>
                <li><a href="#" class="linkedIco" target="_blank" title="Follow me on LinkedIn">Link</a></li>
                <li><a href="#" class="vimeoIco" target="_blank" title="Follow me on Vimeo">Link</a></li>
                <li><a href="#" class="flickrIco" target="_blank" title="Follow me on Flickr">Link</a></li>
            </ul>
        </span>
        </div>

        <h2>John Doe</h2>
        <p>PARTNER & UX/UI DIRECTOR</p>

    </div>


    <!-- Team Member -->
    <div class="large-4 columns teamMember">
        <div class="teamHolder">
        <img alt="" src="http://placehold.it/308x252/0eafff/ffffff.png" />
        <span>
            <p>Pellentesque eros elit integer, sociis, magna odio scelerisque ac, est enim, auctor natoque risus magnis turpis nisi. Montes duis augue, nunc rhoncus ultricies? Porttitor porttitor</p>
            <ul class="teamSocials">
                <li><a href="#" class="faceIco" target="_blank" title="Follow me on Facebook">Link</a></li>
                <li><a href="#" class="twitterIco" target="_blank" title="Follow me on Twitter">Link</a></li>
                <li><a href="#" class="dribbbleIco" target="_blank" title="Follow me on Dribbble">Link</a></li>
                <li><a href="#" class="linkedIco" target="_blank" title="Follow me on LinkedIn">Link</a></li>
                <li><a href="#" class="vimeoIco" target="_blank" title="Follow me on Vimeo">Link</a></li>
                <li><a href="#" class="flickrIco" target="_blank" title="Follow me on Flickr">Link</a></li>
            </ul>
        </span>
        </div>

        <h2>John Doe</h2>
        <p>PARTNER & UX/UI DIRECTOR</p>

    </div>

    <!-- Hiring Container Member -->
    <div class="large-4 columns teamMember">
        <div class="hiringHolder">
            <img src="img/home/case.png" height="87" width="99" alt="Featured Icon">
        </div>

        <h2>We're Hiring</h2>
        <p>Web Developers, Web Designers</p>

    </div>



</div>