<div class="row zindexed introText smallMTop">
    <div class="large-12 columns">
        <h1>What <span>others</span> say <span>about</span> us</h1>
    </div>
</div>

<div id="testimonials" class="row">

    <!-- Testimonial -->
    <div class="large-6 columns testimonialHolder borderBott">
        <div class="row">
            <div class="large-3 columns imageTesti">
                <img alt="" src="http://placehold.it/76x76/0eafff/ffffff.png" />
            </div>
            <div class="large-9 alpha columns testimonialText">
                <p>Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. </p>
                <h5>Jane Austin Doe</h5>
                <h6>Marketing - fedex international</h6>
            </div>
        </div>
    </div>


    <!-- Testimonial -->
    <div class="large-6 columns testimonialHolder borderBott">
        <div class="row">
            <div class="large-3 columns imageTesti">
                <img alt="" src="http://placehold.it/76x76/0eafff/ffffff.png" />
            </div>
            <div class="large-9 alpha columns testimonialText">
                <p>Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. </p>
                <h5>Jane Austin Doe</h5>
                <h6>Marketing - fedex international</h6>
            </div>
        </div>
    </div>


    <!-- Testimonial -->
    <div class="large-6 columns testimonialHolder borderBott">
        <div class="row">
            <div class="large-3 columns imageTesti">
                <img alt="" src="http://placehold.it/76x76/0eafff/ffffff.png" />
            </div>
            <div class="large-9 alpha columns testimonialText">
                <p>Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. </p>
                <h5>Jane Austin Doe</h5>
                <h6>Marketing - fedex international</h6>
            </div>
        </div>
    </div>


    <!-- Testimonial -->
    <div class="large-6 columns testimonialHolder borderBott">
        <div class="row">
            <div class="large-3 columns imageTesti">
                <img alt="" src="http://placehold.it/76x76/0eafff/ffffff.png" />
            </div>
            <div class="large-9 alpha columns testimonialText">
                <p>Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. </p>
                <h5>Jane Austin Doe</h5>
                <h6>Marketing - fedex international</h6>
            </div>
        </div>
    </div>

</div>