<div class="row loveToDo zindexed">
            
    <div class="large-4 columns toDoHolder">
        <span>
            <img src="img/home/icon1.png" alt="Fetured Icon">
        </span>    
        <h5>Ut, placerat ultricies lacus enim amet est, nec risus dapibus</h5>
        <p>Ultricies facilisis est odio. Ac placerat proin aliquet magna porttitor elementum magna, ultrices.</p>
    </div>

    <div class="large-4 columns toDoHolder">
        <span>
            <img src="img/home/icon2.png" alt="Fetured Icon">  
        </span>    
        <h5>Ut, placerat ultricies lacus enim amet est, nec risus dapibus</h5>
        <p>Ultricies facilisis est odio. Ac placerat proin aliquet magna porttitor elementum magna, ultrices.</p>
    </div>

    <div class="large-4 columns toDoHolder">
        <span>
            <img src="img/home/icon3.png" alt="Fetured Icon">
        </span>    
        <h5>Ut, placerat ultricies lacus enim amet est, nec risus dapibus</h5>
        <p>Ultricies facilisis est odio. Ac placerat proin aliquet magna porttitor elementum magna, ultrices.</p>
    </div>

</div>